project:
  type: website
  output-dir: docs

website:
  title: "designbysc"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: NM2207-Week9_Final.qmd
        text: Wk9-Final

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual



